name: Actionsflow

on:
  schedule:
    - cron: "*/5 * * * *"
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      include:
        description: "workflow file filter (glob). Empty means run all."
        required: false
        default: ""
      force:
        description: "force to run workflow, true or false"
        required: false
        default: "false"
      verbose:
        description: "debug workflow, true or false"
        required: false
        default: "false"

jobs:
  run:
    runs-on: ubuntu-latest
    name: Run
    concurrency: actionsflow
    steps:
      - uses: actions/checkout@v4

      - name: Run Actionsflow
        uses: actionsflow/actionsflow-action@v1.3.0
        with:
          args: "build --include ${{ github.event.inputs.include || ''}} -f ${{github.event.inputs.force=='true' && 'true' || 'false'}} --verbose ${{github.event.inputs.verbose=='true' && 'true' || 'false'}}"
          json-secrets: ${{ toJSON(secrets) }}
          json-github: ${{ toJSON(github) }}
