name: Daily News Digest Email

on:
  poll:
    url: https://worldtimeapi.org/api/timezone/Europe/Berlin
    config:
      every: "*/5 * * * *"
      timeZone: Europe/Berlin

jobs:
  send_digest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install feedparser python-dateutil

      - name: Build digest (English)
        run: |
          python scripts/build_digest.py --out digest.md --hours 24 --max-per-section 8

      - name: Send email
        uses: dawidd6/action-send-mail@v7
        with:
          connection_url: ${{ secrets.MAIL_CONNECTION }}
          to: ${{ secrets.MAIL_TO }}
          from: ${{ secrets.MAIL_FROM }}
          subject: Daily News Digest (World/Tech/Economy)
          html_body: file://digest.md
          convert_markdown: true
